version: '2.1'

services:
  dynamo:
    image: tradle/dynamodb-admin
    restart: always
    # dummy credentials
    ports:
      - ${DYNAMO_ADMIN_PORT}:8001
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DYNAMO_ENDPOINT=http://localstack:4569

  # needed for mosca (local MQTT server)
  redis:
    image: tradle/redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /data

  localstack:
    image: localstack/localstack:0.9.0
    restart: always
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "$LOCALSTACK_DATA_DIR:/tmp/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
  tradle_web:
    image: tradle/web-app:localstack
    restart: always
    container_name: tradle-web-app
    restart: always
    ports:
      - "55555:80"
    environment:
      # if url contains any '~' characters, be sure to escape them:
      - DEFAULT_TRADLE_SERVER_URL=${DEFAULT_TRADLE_SERVER_URL}
